BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `VENDEDOR` (
	`VENDEDOR_ID`	INTEGER NOT NULL,
	`NOMBRE`	TEXT,
	`PASS`	TEXT,
	CONSTRAINT `PK_VENDEDOR` PRIMARY KEY(`VENDEDOR_ID`)
);
INSERT INTO `VENDEDOR` (VENDEDOR_ID,NOMBRE,PASS) VALUES (1,'VENDEDOR','1234');
CREATE TABLE IF NOT EXISTS `RUBRO` (
	`RUBRO_ID`	INTEGER NOT NULL,
	`NOMBRE`	TEXT NOT NULL,
	CONSTRAINT `PK_RUBRO` PRIMARY KEY(`RUBRO_ID`),
	CONSTRAINT `UTC_UNIQUE_RUBRO_RUBRO` UNIQUE(`NOMBRE`)
);
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (1,'REMERAS HOMBRE');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (3,'PANTALONES');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (4,'CAMPERAS');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (5,'SLIP');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (6,'BOXER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (7,'PERFUME');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (8,'MEDIAS');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (9,'TIRADORES');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (10,'REMERAS MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (11,'CINTO HOMBRE');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (12,'BILLETERA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (13,'RIÑONERA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (15,'BOLSO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (16,'MOCHILA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (17,'PANTALON HOMBR');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (18,'MALLA HOMBRE');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (19,'MUSCULOSA HOMB');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (20,'CAMISAS HOMBRE');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (21,'ROMPEVIENTO HO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (22,'BERMUDA HOMBRE');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (23,'JOGER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (24,'TOP MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (25,'JARDINERO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (26,'VESTIDO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (27,'ACCESORIOS');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (29,'BABUCHA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (30,'BLAZER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (32,'BLUSA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (33,'BOMBACHA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (34,'CALZA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (35,'CAMISA MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (36,'CAPRI');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (37,'CONJUNTO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (38,'CAMPERA MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (39,'CORPIÑO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (40,'JEAN MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (41,'KIMONO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (42,'MALLA MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (43,'MEDIAS MUJE');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (45,'MUSCULOSA MUJE');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (46,'PALAZO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (47,'PANTALON MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (48,'PESCADOR');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (49,'POLLERA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (50,'SACO MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (51,'SHORT MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (52,'SOQUETE MUJER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (53,'SURTIDO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (54,'TORRERITA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (55,'BODY');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (56,'SUETER');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (57,'BAHIANO');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (58,'SUDADERA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (59,'PIJAMA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (60,'TORERITA');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (61,'CANCAN');
INSERT INTO `RUBRO` (RUBRO_ID,NOMBRE) VALUES (62,'GORRAS');
CREATE TABLE IF NOT EXISTS `PROVEEDOR` (
	`PROVEEDOR_ID`	INTEGER NOT NULL,
	`NOMBRE`	TEXT NOT NULL,
	CONSTRAINT `UTC_UNIQUE_PROVEEDOR_PROVEEDOR` UNIQUE(`NOMBRE`),
	CONSTRAINT `PK_PROVEEDOR` PRIMARY KEY(`PROVEEDOR_ID`)
);
INSERT INTO `PROVEEDOR` (PROVEEDOR_ID,NOMBRE) VALUES (1,'PROVEEDOR');
CREATE TABLE IF NOT EXISTS `MARCA` (
	`MARCA_ID`	INTEGER NOT NULL,
	`NOMBRE`	TEXT NOT NULL,
	CONSTRAINT `UTC_UNIQUE_MARCA_MARCA` UNIQUE(`NOMBRE`),
	CONSTRAINT `PK_MARCA` PRIMARY KEY(`MARCA_ID`)
);
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (1,'KOSIUKO');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (2,'BUENOS AIRES');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (3,'ZIMITH');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (4,'CAPITAN');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (5,'KOLPER');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (6,'NASA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (7,'ELEMENT');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (8,'TRONO');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (9,'FUSTON');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (10,'KIKA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (11,'CORRIENTES');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (12,'CUERDA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (13,'MONAME');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (14,'YOOMITO');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (15,'PAULINA LO');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (16,'ABSTRACTA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (17,'ACTIVITY');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (18,'ANA REINA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (20,'BORA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (21,'CATALINA HIDALGO');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (22,'CINDISAMI');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (23,'COCOT');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (24,'CRISANTA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (25,'DOROTHY');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (26,'DUAL POWER');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (27,'EVNI');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (28,'FELICIA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (29,'FINI');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (30,'FORNARINA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (31,'HUNGRIA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (32,'IMPORTADA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (33,'INFINITE');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (34,'LITIO');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (35,'LOVE THIS');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (37,'MINTAGE');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (38,'MUNDO');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (39,'NOT');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (40,'SMASH');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (41,'SURTIDO');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (42,'SWEET');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (43,'VOUS');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (44,'YD');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (46,'MARIQUITA');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (48,'BLACK SHEEP');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (49,'Q7');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (50,'DIMPLAY');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (51,'KICKBACK');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (52,'LADY FIT');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (53,'NIKE');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (54,'AIRFIND');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (55,'AIRWIND');
INSERT INTO `MARCA` (MARCA_ID,NOMBRE) VALUES (56,'LF3');
CREATE TABLE IF NOT EXISTS `CLIENTE` (
	`CLIENTE_ID`	INTEGER NOT NULL,
	`NOMBRE`	TEXT NOT NULL,
	`DOMICILIO`	TEXT,
	`TELEFONO`	INTEGER NOT NULL,
	`CREDITO`	REAL NOT NULL DEFAULT 0,
	CONSTRAINT `PK_CLIENTE` PRIMARY KEY(`CLIENTE_ID`)
);
INSERT INTO `CLIENTE` (CLIENTE_ID,NOMBRE,DOMICILIO,TELEFONO,CREDITO) VALUES (1,'CONSUMIDOR FINAL','NO',0,0.0);
COMMIT;
