SELECT ARTICULO.ARTICULO_ID,
       ARTICULO.CODIGO,
       ARTICULO.DESCRIPCION,
       ARTICULO.PRECIO_LISTA,
       ARTICULO.PRECIO_CONTADO,
       ARTICULO.PRECIO_COSTO,
       ARTICULO.STOCK,
       RUBRO.NOMBRE AS RUBRO,
       MARCA.NOMBRE AS MARCA,
       ARTICULO.PROMO_BOOL,
       ARTICULO.PRECIO_PROMO
FROM ARTICULO
INNER JOIN MARCA
  ON ARTICULO.MARCA_ID = MARCA.MARCA_ID
INNER JOIN RUBRO 
  ON ARTICULO.RUBRO_ID = RUBRO.RUBRO_ID



SELECT ARTICULO.CODIGO,
       ARTICULO.RUBRO,
       ARTICULO.DESCRIPCION,
       ARTICULO.MARCA,
       ARTICULO.PRECIO_LISTA,
       ARTICULO.PRECIO_COSTO,
       ARTICULO.STOCK

INSERT INTO `READ_ARTICULOS_PROCESED` () VALUES ('ZH2932047942','22','BERMUDA JEAN SILSAN TALLE 42','3','1300','550','1'),
